name: docker
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
      -
        name: build and test
        run: |
          docker build -t test --no-cache .
          sudo cp -rv run/* /run
          docker run -d \
            -p 8080:8080 \
            -v /run/configs/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro \
            -v /run/secrets/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro \
            test
          while true
            do
              sleep 10
              docker ps | grep Up && break
            done
          while true
            do
              sleep 10
              curl localhost:8080 -I | grep 200 && break
            done
